services:
  recollection:
    build: .
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    command: ["./recollection"]

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
