services:
  recollection:
    networks:
      - recollection-network
    build: .
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    command: ["./recollection"]

  db:
    image: postgres
    networks:
      recollection-network:
        aliases:
          - db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

networks:
  recollection-network:
